import { StyleSheet } from 'react-native';

export const AZUL = '#4EB8E8';
export const AMARELO = '#F0B429';
export const ICONE = '#5BA3C9';

export const estilos = StyleSheet.create({
  tela: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  caixa: {
    flex: 1,
    width: '100%',
    zIndex: 1,
  },
  topo: {
    backgroundColor: 'transparent',
    paddingHorizontal: 20,
    paddingBottom: 12,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: 12,
  },
  topoTitulo: {
    color: '#ffffff',
    fontWeight: 'bold',
    fontSize: 20,
  },
  tagBoasVindas: {
    marginLeft: 'auto',
    backgroundColor: 'rgba(255, 255, 255, 0.28)',
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 4,
    maxWidth: 140,
  },
  tagBoasVindasTexto: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  flex: {
    flex: 1,
  },
  conteudo: {
    flex: 1,
    paddingHorizontal: 28,
    paddingTop: 24,
    paddingBottom: 80,
  },
  conteudoCurto: {
    paddingHorizontal: 28,
    paddingTop: 16,
    paddingBottom: 80,
  },
  voltarLinha: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    gap: 8,
  },
  tituloPedido: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  etapa: {
    flexDirection: 'row',
    minHeight: 44,
  },
  etapaEsquerda: {
    width: 24,
    alignItems: 'center',
  },
  circulo: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#ffffff',
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  circuloOk: {
    backgroundColor: '#ffffff',
    borderColor: '#ffffff',
  },
  circuloAtual: {
    borderWidth: 3,
    borderColor: AMARELO,
    backgroundColor: '#ffffff',
  },
  linhaEtapa: {
    width: 2,
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    marginVertical: 2,
  },
  linhaOk: {
    backgroundColor: '#ffffff',
  },
  etapaTexto: {
    flex: 1,
    paddingLeft: 12,
    paddingBottom: 16,
  },
  etapaNome: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  etapaData: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.85)',
    marginTop: 2,
  },
  dataCard: {
    fontSize: 12,
    color: '#888888',
    marginTop: 2,
  },
  card: {
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
    gap: 12,
  },
  cardTexto: {
    flex: 1,
  },
  cardTitulo: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#3d4a52',
    marginBottom: 2,
  },
  cardLinha: {
    fontSize: 13,
    color: '#5c6b73',
    marginTop: 2,
  },
  statusPedido: {
    marginTop: 8,
    fontSize: 13,
    fontWeight: 'bold',
    color: AMARELO,
  },
  statusCancelado: {
    marginTop: 8,
    fontSize: 13,
    fontWeight: 'bold',
    color: '#c0392b',
  },
  tituloSecao: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#ffffff',
    marginTop: 8,
    marginBottom: 10,
  },
  barraFundo: {
    height: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.45)',
    borderRadius: 8,
    overflow: 'hidden',
    marginBottom: 8,
  },
  barraPreenchida: {
    height: 10,
    backgroundColor: AMARELO,
    borderRadius: 8,
  },
  pontoAoVivo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  bolinhaViva: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ffffff',
  },
  rotulo: {
    fontSize: 14,
    color: '#ffffff',
    marginBottom: 6,
    fontWeight: '600',
  },
  itemMenu: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#ffffff',
    borderRadius: 14,
    paddingVertical: 16,
    paddingHorizontal: 14,
    marginBottom: 10,
  },
  itemMenuTexto: {
    fontSize: 16,
    color: '#3d4a52',
    fontWeight: '600',
  },
  pastaLinha: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  fundoMenu: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    justifyContent: 'center',
    padding: 28,
  },
  caixaMenuPedido: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 8,
  },
  botaoMenuPedido: {
    padding: 8,
    marginLeft: 'auto',
  },
  logo: {
    alignItems: 'center',
    marginBottom: 20,
  },
  logoIcone: {
    alignItems: 'center',
    marginBottom: 4,
  },
  logoIconeGrande: {
    alignItems: 'center',
    marginBottom: 12,
  },
  logoPin: {
    marginBottom: -8,
  },
  nomeApp: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#ffffff',
    marginTop: 4,
  },
  nomeAppGrande: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#ffffff',
    marginTop: 8,
  },
  caminhao: {
    fontSize: 48,
  },
  subtitulo: {
    fontSize: 15,
    color: '#ffffff',
    marginTop: 8,
    textAlign: 'center',
  },
  tituloPagina: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 20,
    textAlign: 'center',
  },
  campo: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 0,
    borderRadius: 14,
    paddingHorizontal: 14,
    marginBottom: 14,
    backgroundColor: '#ffffff',
  },
  icone: {
    marginRight: 10,
  },
  input: {
    flex: 1,
    paddingVertical: 14,
    fontSize: 15,
    color: '#3d4a52',
  },
  botao: {
    backgroundColor: AMARELO,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
  },
  botaoTexto: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  botaoSecundario: {
    marginTop: 12,
    backgroundColor: AMARELO,
    borderWidth: 0,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
  },
  botaoSecundarioTexto: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  link: {
    color: '#ffffff',
    textAlign: 'center',
    marginTop: 16,
    fontSize: 14,
    fontWeight: '600',
  },
  textoAjuda: {
    color: '#ffffff',
    textAlign: 'center',
    marginTop: 14,
    fontSize: 13,
  },
  rodape: {
    paddingHorizontal: 24,
    paddingBottom: 28,
    paddingTop: 12,
    alignItems: 'center',
  },
  bolinhas: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  bolinha: {
    width: 8,
    height: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.45)',
    borderRadius: 4,
    marginHorizontal: 4,
  },
  bolinhaAtiva: {
    backgroundColor: AMARELO,
  },
  rodapeTitulo: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 6,
  },
  rodapeTexto: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.9)',
    textAlign: 'center',
  },
  deserto: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 140,
  },
  duna: {
    position: 'absolute',
    left: -40,
    right: -40,
    bottom: -30,
    height: 90,
    backgroundColor: '#E09A32',
    borderTopLeftRadius: 180,
    borderTopRightRadius: 180,
  },
  cactoLonge: {
    position: 'absolute',
    left: 48,
    bottom: 42,
    alignItems: 'center',
  },
  cactoHastePequena: {
    width: 8,
    height: 28,
    backgroundColor: '#6BB3C9',
    borderRadius: 4,
  },
  cactoPerto: {
    position: 'absolute',
    right: 36,
    bottom: 28,
    width: 54,
    height: 90,
    alignItems: 'center',
  },
  cactoVaso: {
    position: 'absolute',
    bottom: 0,
    width: 36,
    height: 22,
    backgroundColor: AMARELO,
    borderRadius: 4,
  },
  cactoHaste: {
    position: 'absolute',
    bottom: 18,
    width: 16,
    height: 52,
    backgroundColor: '#6BB3C9',
    borderRadius: 8,
  },
  cactoBracoEsq: {
    position: 'absolute',
    bottom: 42,
    left: 4,
    width: 18,
    height: 10,
    backgroundColor: '#6BB3C9',
    borderRadius: 6,
  },
  cactoBracoDir: {
    position: 'absolute',
    bottom: 50,
    right: 4,
    width: 16,
    height: 10,
    backgroundColor: '#6BB3C9',
    borderRadius: 6,
  },
});
